### ISSUE TITLE
Add "internet" node to /etc/hosts on oob-mgmt-server

### ISSUE THREAD

**Issue by ddutt** [CumulusNetworks/cldemo-vagrant#23]
The node "internet" is only accessible via vagrant. This needs to be accessible via oob-mgmt-server as well. I use this to provision the BGP peering between internet and exit leaves.

**Comment by ericpulvino** [comment]
Group has agreed to add this MAC address and DHCP mapping for eth0 of "internet" device.

A0:00:00:00:00:f3 --> 192.168.1.253

Will make a new branch for this and do some light checking to make sure it doesn't destroy anything but since most demos do not use that device I do not anticipate much heartburn.

**Comment by seanx820** [comment]
we also need to add this to /etc/hcp/dhcpd.hosts

**Comment by ericpulvino** [comment]
Done. Group settled on 
`
host internet {hardware ethernet a0:00:00:00:00:50; fixed-address 192.168.0.253; option host-name "internet"; option cumulus-provision-url "http://192.168.0.254/ztp_oob.sh";  }
`
