### ISSUE TITLE
Missing interfaces

### ISSUE THREAD

**Issue by benpiper** [CumulusNetworks/cldemo-vagrant#48]
There seem to be interfaces missing. For example:

```
> cumulus@leaf01:~$ net add interface
>     <interface>  :  An interface name "swp1" or glob "swp1-4,6,10-12"
>     lo           :  interface
>     eth0         :  LLDP peer oob-mgmt-switch
>     swp1         :  interface
>     swp2         :  interface
>     swp45        :  interface
>     swp46        :  interface
>     swp47        :  interface
>     swp48        :  interface
>     vagrant      :  interface

```

This doesn't occur in the cl3.6.2 branch.

VirtualBox 5.2.10
Vagrant 2.0.2

**Comment by ericpulvino** [comment]
We've just discovered this issue in 3.7.0 Vx for Vagrant on the Virtualbox hypervisor.
Changes in the VX build process have resulted in this regression from 3.6.2 --> 3.7.0. 
There are two ways to address this (and we're doing both):

1). We're working to re-release 3.7.0 VX for Vagrant Virtualbox to predefine all the interfaces with the appropriate virtio driver.
2). I'm putting a patch into Topology Converter to generate the appropriate driver config for each interface in the Vagrantfile. See commit: https://github.com/CumulusNetworks/topology_converter/commit/2bb01961383cfa3866c6e586d5b5b17d12b56814

As I've just regenerated this branch with the configuration workaround from Topology Converter the issue should be solved. Let me know if otherwise @benpiper Thanks!
